# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=100, unique=True)),
                ('expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[(b'available', b'available'), (b'notavailable', b'notavailable')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=100, unique=True)),
                ('purchased_user_email', models.CharField(max_length=100)),
            ],
        ),
    ]
