# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_code', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherpurchase',
            old_name='purchased_user_email',
            new_name='given_to',
        ),
        migrations.RemoveField(
            model_name='vouchercode',
            name='status',
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucherpurchase',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher_code.VoucherCode'),
        ),
    ]
