# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_code', '0003_auto_20190131_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpurchase',
            name='product_title',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
